[package]
name = "vim-driver"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
queues = "1.0.2"
strum = "0.24"
strum_macros = "0.24"
libc = "0.2"

[build-dependencies]
bindgen = "*"
